[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sumitshuklaa", email = "sumitsh66@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "faiss-cpu>=1.15.0",
    "huggingface-hub>=1.29.0",
    "ipykernel>=7.3.0",
    "langchain>=1.3.17",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.0",
    "pymupdf>=1.28.2",
    "pypdf>=6.16.2",
    "sentence-transformers>=6.0.0",
]

[project.scripts]
rag = "rag:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
